syntax on
set incsearch
set hlsearch
set ruler
set laststatus=2
set title
set background=dark
set runtimepath^=~/.vim/bundle/vim-sensible
set runtimepath^=~/.vim/bundle/ctrlp.vim
set runtimepath^=~/.vim/bundle/vim-fugitive
