# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [ "amd_pstate=active" ];

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/48b5a0da-b66c-490d-bd96-d16690153a51";
    allowDiscards = true;
  };

  boot.initrd.systemd.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a918edd-35ea-4a60-acde-da39ff065f1a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E201-1128";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # swapDevices = [{
  #   device = "/var/lib/swapfile";
  #   size = 64*1024;
  # }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = false;
  # networking.interfaces.enp193s0f3u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = false;


  systemd.network = {
    enable = true;
    networks."10-wireless" = {
      matchConfig.Name = "wlp1s0";
      networkConfig.DHCP = "yes";
      dhcpV4Config.RouteMetric = 600;
    };
    networks."20-ethernet" = {
      matchConfig.Name = "enp*";
      # networkConfig.DHCP = "yes";
      # dhcpV4Config.RouteMetric = 100;
      address = [
        "10.50.0.2/24"
      ];
    };
  };

  services.resolved.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.enableRedistributableFirmware = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;

  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
}
