#!/bin/sh

case $1 in
    post)
	/sbin/hdparm -B 255 /dev/sda
        if on_ac_power; then
                /usr/sbin/pm-powersave false
        else
                /usr/sbin/pm-powersave true
        fi
    ;;
esac
exit 0

