Section "Device"
    Identifier     "Device0"
    Option         "Monitor-DVI-0" "Monitor0"
    Option         "Monitor-DVI-1" "Monitor1"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    Option         "RandRRotation" "on"
    Option         "Rotate" "Left"
EndSection

Section "Monitor"
    Identifier     "Monitor1"
    Option         "RightOf" "Monitor0"
    Option         "RandRRotation" "on"
    Option         "Rotate" "Left"
EndSection
